'use strict';const Get=Id=>document.getElementById(Id);let WorkerJob=null,Token=0,Timer=null;
function Stop(){Token++;clearTimeout(Timer);Timer=null;if(WorkerJob)WorkerJob.terminate();WorkerJob=null;Get('read').disabled=false;Get('check').disabled=false;Get('cancel').hidden=true;Get('columns').querySelectorAll('input').forEach(E=>E.disabled=false);}
function Hide(){Get('selection').hidden=true;Get('result').hidden=true;Get('columns').textContent='';Get('warnings').textContent='';Get('summary').textContent='';Get('selected').textContent='';Get('status').textContent='';Get('error').textContent='';}
function Fail(Message){Stop();Hide();Get('error').textContent=Message;}
function Busy(Message){Get('columns').querySelectorAll('input').forEach(E=>E.disabled=true);Get('status').textContent=Message;Get('read').disabled=true;Get('check').disabled=true;Get('cancel').hidden=false;Timer=setTimeout(()=>Fail('The job took more than 30 seconds and stopped. No report was produced.'),30000);}
function Idle(){Get('columns').querySelectorAll('input').forEach(E=>E.disabled=false);clearTimeout(Timer);Timer=null;Get('read').disabled=false;Get('check').disabled=false;Get('cancel').hidden=true;Get('status').textContent='';}
Get('file').addEventListener('change',()=>{Stop();Hide();});Get('clear').addEventListener('click',()=>{Stop();Hide();Get('file').value='';Get('status').textContent='Cleared. File data and report removed from this tool.';Get('file').focus();});Get('cancel').addEventListener('click',()=>{Stop();Hide();Get('status').textContent='Cancelled. No report kept. Read the file again to continue.';Get('read').focus();});
Get('read').addEventListener('click',()=>{Stop();Hide();const File=Get('file').files[0];if(!File){Fail('Choose a file first.');Get('file').focus();return;}if(File.size>1048576){Fail('File exceeds 1 MiB (1,048,576 bytes).');return;}if(!window.Worker||!window.TextDecoder){Fail('This browser cannot run this local check. Use the Python guide.');return;}const Current=Token;
try{WorkerJob=new Worker('worker.js');}catch(E){Fail('The local worker could not start. No report was produced.');return;}
WorkerJob.onerror=()=>{if(Current===Token)Fail('The local worker failed. No report was produced.');};WorkerJob.onmessage=({data})=>{if(Current!==Token)return;Idle();if(data.error){Fail(data.error);return;}if(data.header){Get('columns').textContent='';data.header.forEach((Name,I)=>{const Label=document.createElement('label'),Input=document.createElement('input'),Text=document.createElement('span');Input.type='checkbox';Input.value=I;Text.textContent='Column '+(I+1)+': '+Name;Label.append(Input,Text);Get('columns').append(Label);Input.addEventListener('change',()=>{Get('result').hidden=true;Get('warnings').textContent='';Get('summary').textContent='';Get('selected').textContent='';});});Get('selection').hidden=false;Get('selection-title').focus();}else if(data.report){const R=data.report;Get('summary').textContent=R.records+' records checked; '+R.warnings.length+' flagged cells. '+(R.warnings.length?'Review import settings for these positions.':'No warnings for the two tested digit-string patterns.');Get('selected').textContent='Selected column positions: '+R.columns.join(', ');Get('warnings').textContent='';R.warnings.forEach(W=>{const Tr=document.createElement('tr');[W.record,W.line,W.column,W.risks.join('; ')].forEach(V=>{const Td=document.createElement('td');Td.textContent=V;Tr.append(Td);});Get('warnings').append(Tr);});Get('result').hidden=false;Get('result-title').focus();}else Fail('Incomplete response. No report was produced.');};Busy('Reading on this device. Nothing is uploaded.');try{WorkerJob.postMessage({file:File});}catch(E){Fail('The file could not be read by the worker.');}});
Get('check').addEventListener('click',()=>{Get('result').hidden=true;Get('error').textContent='';const Indices=Array.from(Get('columns').querySelectorAll('input:checked'),E=>Number(E.value));if(!Indices.length){Get('error').textContent='Choose at least one identifier column.';return;}if(!WorkerJob){Fail('Read the file again before checking.');return;}Busy('Checking selected columns on this device.');try{WorkerJob.postMessage({indices:Indices});}catch(E){Fail('The selected columns could not be checked.');}});
