'use strict';
const MAX_FILES=1000,MAX_FILE_BYTES=16777216,MAX_TOTAL_BYTES=268435456,MAX_MANIFEST_BYTES=1048576;
const Own=(o,k)=>Object.prototype.hasOwnProperty.call(o,k);
function Exact(o,keys){return o&&typeof o==='object'&&!Array.isArray(o)&&Object.keys(o).sort().join('|')===keys.slice().sort().join('|');}
function PathKey(s){if(typeof s!=='string'||!s||s.length>4096||/[\\\x00-\x1f\x7f]/.test(s)||s.startsWith('/')||/^[a-z]:/i.test(s)||s.split('/').some(p=>!p||p==='.'||p==='..'))throw Error('Invalid relative file path.');return s.normalize('NFC').toLowerCase();}
function UniquePaths(entries){const seen=new Set();for(const e of entries){const k=PathKey(e.path);if(seen.has(k))throw Error('Duplicate or case/Unicode-ambiguous paths. Rename those files or use a different selection.');seen.add(k);}}
// Bounded JSON parser: JSON.parse alone silently accepts duplicate object keys.
function ReadJson(text){let i=0,n=0;const ws=()=>{while(/[\x20\x09\x0a\x0d]/.test(text[i]||'!'))i++;};function str(){let start=i++;while(i<text.length){const c=text[i++];if(c==='"')return JSON.parse(text.slice(start,i));if(c==='\\')i++;if(c.charCodeAt(0)<32)throw Error('Invalid JSON string.');}throw Error('Unfinished JSON string.');}
function v(depth){if(depth>8||++n>20000)throw Error('Manifest JSON is too complex.');ws();let c=text[i];if(c==='"')return str();if(c==='{'){i++;let o=Object.create(null);ws();if(text[i]==='}'){i++;return o;}for(;;){ws();if(text[i]!=='"')throw Error('Invalid JSON object.');let k=str();if(Own(o,k))throw Error('Repeated JSON key in manifest.');ws();if(text[i++]!==':')throw Error('Invalid JSON object.');o[k]=v(depth+1);ws();c=text[i++];if(c==='}')return o;if(c!==',')throw Error('Invalid JSON object.');}}if(c==='['){i++;let a=[];ws();if(text[i]===']'){i++;return a;}for(;;){a.push(v(depth+1));ws();c=text[i++];if(c===']')return a;if(c!==',')throw Error('Invalid JSON array.');}}let match=/^(?:true|false|null|-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?)/.exec(text.slice(i));if(!match)throw Error('Invalid JSON value.');i+=match[0].length;return JSON.parse(match[0]);}
let out=v(0);ws();if(i!==text.length)throw Error('Extra data after manifest JSON.');return out;}
function ReadManifest(text){const m=ReadJson(text);if(!Exact(m,['schema','algorithm','mode','created','entries'])||m.schema!==1||m.algorithm!=='SHA-256'||!['files','folder'].includes(m.mode)||typeof m.created!=='string'||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(m.created)||!Number.isFinite(Date.parse(m.created))||!Array.isArray(m.entries)||!m.entries.length||m.entries.length>MAX_FILES)throw Error('Unsupported or malformed manifest. Use a manifest made by this tool.');let total=0;for(const e of m.entries){if(!Exact(e,['path','bytes','sha256'])||!Number.isSafeInteger(e.bytes)||e.bytes<0||e.bytes>MAX_FILE_BYTES||typeof e.sha256!=='string'||!/^[a-f0-9]{64}$/.test(e.sha256))throw Error('Invalid manifest entry.');PathKey(e.path);if(m.mode==='files'&&e.path.includes('/'))throw Error('File-selection manifest contains a folder path.');total+=e.bytes;}if(total>MAX_TOTAL_BYTES)throw Error('Manifest exceeds total size limit.');UniquePaths(m.entries);return m;}
function Selection(files,mode){if(!['files','folder'].includes(mode)||!files.length||files.length>MAX_FILES)throw Error('Choose 1 to 1,000 files.');let root=null,total=0;const entries=Array.from(files,f=>{let path=f.name;if(mode==='folder'){let parts=(f.webkitRelativePath||'').split('/');if(parts.length<2||!parts[0])throw Error('This browser did not supply relative folder paths. Use the individual-files picker.');if(root===null)root=parts[0];if(root!==parts[0])throw Error('Choose one folder at a time.');path=parts.slice(1).join('/');}PathKey(path);if(mode==='files'&&path.includes('/'))throw Error('Invalid selected filename.');if(!Number.isSafeInteger(f.size)||f.size<0)throw Error('Invalid selected file size.');total+=f.size;return {path,file:f};});if(total>MAX_TOTAL_BYTES)throw Error('Selected files exceed 256 MiB in total. Choose a smaller selection.');UniquePaths(entries);return entries.sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:0);}
function Compare(current,baseline){const before=new Map(baseline.entries.map(e=>[e.path,e])),rows=[];for(const c of current){const old=before.get(c.path);before.delete(c.path);if(c.state!=='hashed')rows.push({path:c.path,state:c.state});else rows.push({path:c.path,state:!old?'added':old.bytes===c.bytes&&old.sha256===c.sha256?'unchanged':'changed'});}for(const path of before.keys())rows.push({path,state:'not-selected'});rows.sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:0);return rows;}
if(typeof module!=='undefined')module.exports={ReadJson,ReadManifest,Selection,Compare,PathKey,MAX_FILE_BYTES};
